const { getDefaultConfig } = require('expo/metro-config');
const fs   = require('fs');
const path = require('path');
const Papa = require('papaparse');

const DATA_DIR  = path.join(__dirname, 'assets/data');
const OUT_PATH  = path.join(__dirname, 'src/data/registry.ts');

// ── Registry generator ────────────────────────────────────────────────────────

function toLabel(filename) {
  return path.basename(filename, '.csv')
    .replace(/[_-]/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase())
    .replace(/\b([AaBbCc][12])\b/g, s => s.toUpperCase());
}
function toIcon(filename) {
  const n = filename.toLowerCase();
  if (/[ab][12]|vocab|word|dict|glossar/.test(n)) return '📚';
  if (/transl|i18n|locale|string|ui/.test(n))     return '🖥️';
  if (/phrase|convers/.test(n))                    return '💬';
  return '📝';
}
function toDescription(headers, count) {
  if (headers.some(h => /^(de|en|fr)_word$/.test(h)))
    return `${count} vocab entries with example sentences`;
  if (headers.includes('key') && ['en','de','fr'].some(l => headers.includes(l)))
    return `${count} UI translation strings`;
  return `${count} entries`;
}

function syncRegistry() {
  try {
    const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.csv')).sort();
    const datasets = files.map(filename => {
      const content  = fs.readFileSync(path.join(DATA_DIR, filename), 'utf8');
      const { data } = Papa.parse(content, { header: true, skipEmptyLines: true,
                                              transformHeader: h => h.trim() });
      const headers  = data.length ? Object.keys(data[0]) : [];
      const id       = path.basename(filename, '.csv').replace(/[^a-zA-Z0-9]/g, '_');
      return { id, label: toLabel(filename), icon: toIcon(filename),
               description: toDescription(headers, data.length),
               count: data.length, content };
    });

    const ts =
`// AUTO-GENERATED by metro.config.js — do not edit manually.
// Re-generated on every Metro start and whenever a CSV in assets/data/ changes.

export interface DatasetMeta {
  id:          string;
  label:       string;
  icon:        string;
  description: string;
  count:       number;
  content:     string;
}

export const CSV_REGISTRY: DatasetMeta[] = ${JSON.stringify(datasets, null, 2)};
`;
    fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
    fs.writeFileSync(OUT_PATH, ts, 'utf8');
    console.log(
      `[LingoCheck] registry.ts — ${datasets.length} dataset(s): ` +
      datasets.map(d => d.id).join(', ')
    );
  } catch (err) {
    console.error('[LingoCheck] registry sync failed:', err.message);
  }
}

// Run once at startup so the registry is always fresh when Metro launches
syncRegistry();

// Watch assets/data/ — regenerate whenever a CSV is added, removed, or updated
let debounce = null;
fs.watch(DATA_DIR, (_evt, filename) => {
  if (!filename?.endsWith('.csv')) return;
  clearTimeout(debounce);
  debounce = setTimeout(() => {
    console.log(`[LingoCheck] ${filename} changed — refreshing registry…`);
    syncRegistry();
  }, 150);
});

// ── Metro config ──────────────────────────────────────────────────────────────

const config = getDefaultConfig(__dirname);
config.resolver.assetExts.push('csv');
module.exports = config;
