// AUTO-GENERATED by metro.config.js — do not edit manually.
// Re-generated on every Metro start and whenever a CSV in assets/data/ changes.

export interface DatasetMeta {
  id:          string;
  label:       string;
  icon:        string;
  description: string;
  count:       number;
  content:     string;
}

export const CSV_REGISTRY: DatasetMeta[] = [];
